version: "3.9"

services:
  app:
    build: .
    container_name: trafficmagnit_app
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - ./:/app

  nginx:
    image: nginx:stable
    container_name: trafficmagnit_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
